{% set name = "fs.onedatarestfs" %}
{% set version = "21.2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fs_onedatarestfs-{{ version }}.tar.gz
  sha256: 0c0bd755eeef956435f266ca78356cdc1e0ed5b844ab71cb4b7c5aa821f64f69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fs
    - onedatafilerestclient

test:
  imports:
    - fs.onedatarestfs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/onedata/onedatarestfs
  summary: Onedata REST-based filesystem for PyFilesystem
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bgruening
